[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.142.2",
    "numpy>=2.4.6",
    "opencv-python-headless>=5.0.0.93",
    "pillow>=12.3.0",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.4",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
    "uvicorn>=0.54.0",
    "web3>=8.0.0",
]
